### ISSUE TITLE
garage door status not working

### ISSUE THREAD

**Issue by seanfilyaw** [andres-leon/garage-door-controller#1]
I have set up my garage with your code and set up other than the magnetic sensors, I set up a wire between the factory garage switch. One wire to the open side, one wire to the closed side. When the garage door is closed it completes the ground circuit. The "status" doesn't seem to work. Maybe something I have wrong. 

The other main problem I have is when you hit the toggle switch in Home Assistant the light showing activation On the relay stays on. I can hit the toggle switch in Home Assistant once more and make it go off, I was just wondering if you might have any patches to fix this, or if you might have ran into the same problem?

**Comment by andres-leon** [comment]
I would try testing the magnetic sensor independently and make sure it works on its own. Make sure the Pi is able to read the sensor and that it properly detects when it is near and far. Once you get that working then put it together with the garage setup and test it again. I had some issues making sure the sensor worked at first, too.

Is there garage activating when you toggle the HASS switch? The function gdo_relay() (line 73 of [garagecontroller.py](https://github.com/andres-leon/garage-door-controller/blob/master/garagecontroller.py#L73) ) controls when the relay opens and closes. Make sure that the relay output goes false, then wait about half a second, and then set it back to true.

**Comment by seanfilyaw** [comment]
It does but I have to turn the switch to the on position to turn the relay
off

**Comment by andres-leon** [comment]
Not really sure what's causing that. I got my code working by tweaking it and modifying the sleep timing too. perhaps your garage opener works differently.

**Comment by seanfilyaw** [comment]
I was able to get it to work after adding the ac reed switch, instead of
trying to use the limit switches on the garage door railing
