### ISSUE TITLE
Problem with MQTT

### ISSUE THREAD

**Issue by oldeck** [andres-leon/garage-door-controller#2]
I got your script to work but I had to make this change:

import mosquitto
client = mosquitto.Mosquitto()

becomes
import paho.mqtt.client as paho
client = paho.Client()

Thanks for the program.  Can you post more about your camera program?  I want to add the same capability.

**Comment by andres-leon** [comment]
Yes. i noticed that in newer implementations they changed the names. Good catch!

As far as the camera is concerned, I used RPi cam controller (http://elinux.org/RPi-Cam-Web-Interface) and then used the camera component in HASS to link the image to it. You, of course, need a camera attached to the Pi. the website I linked to has all the information and directions you need to install and configure the camera.
